name: dda
base: core18 # the base snap is the execution environment for this snap
version: '0.1+git'
summary: DuckDuckGo Instant Answers API brought to your terminal  # 79 char long summary
description: |
  Fetch a quick answer from your terminal. `dda spell convinient`, `dda ip`, `dda password 15`,
  and many more queries supported by DDG Instant Answer API. No need to retype your search in
  a browser window, if you need to drill down into answers. `dda` will open DuckDuckGo search
  window with your query.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # 'devmode', 'strict'

parts:
  dda:
    plugin: python
    python-version: python3
    source: .
    requirements:
      - requirements.txt

apps:
  dda:
    command: bin/dda
