name: dda
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: DuckDuckGo Instant Answers API brought to your terminal  # 79 char long summary
description: |
  Fetch a quick answer from your terminal. `dda spell convinient`, `dda ip`, `dda password 15`,
  and many more queries supported by DDG Instant Answer API. No need to retype your search in
  a browser window, if you need to drill down into answers. `dda` will open DuckDuckGo search
  window with your query.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
